### PR TITLE
Charlie

### PR DESCRIPTION
**Pull request by belmontrevenge**
This includes the fixes to those errors we saw in class today!
Dina, please check out the DatabaseHandler.py class.  I changed some function names that you may be using in your code.  If it's too much of a hassle we can change back.

Also added some small error handling for get_db_dir() in the global config.  It shouldn't have an impact an anything.

### CODE REVIEW

**Comment by dsteeve** [comment]
ok.  I added in the fix that Charlie pointed out.  I also added in a global config file so we no longer hardcode reporting server host and port and the 'eventDateTime' name.  I also fixed up tests.

**Comment by dsteeve** [comment]
👍  for charlie's stuff.

**Comment by rsorensen-lb** [comment]
:+1:

**Comment by benphillips989** [comment]
:+1:

**Pull request merged**
