### PR TITLE
added some database modules and tests

### PR DESCRIPTION
**Pull request by benphillips989**
I created three modules
DB_Init.py which can easily create a sqlite database
Table_Init.py which can easily create a table and columns
Table_Insert.py which can handle variable length insert statements by using a list

I will go over on tuesday, I still need to learn pydoc or sphinx or something.
would like to pull to dev

Thanks,
Ben

### CODE REVIEW

**Comment by jnels124** [comment]
:+1:

**Comment by dsteeve** [comment]
:+1: tests and everything.  yay!

**Comment by dsteeve** [comment]
Hey Ben,
I have a couple suggestions on this we can discuss Tues.
1.  the tests should go into the test directory under src, this way the database dir is just necessary code we can package up.  (however, this may cause us grief ... so let's discuss issues with it)
2. eventually we will need to unhard-code the './honeyDB/honeyDB.sqlite' and all the hardcoded references to location.  The reporting piece of this will also need this and the users may want to configure the location.  Therefore we might need a configure.py or something like that and put it somewhere where it can be shared.

But for now... good first step.

**Comment by benphillips989** [comment]
Hello,

1) We can put tests where ever you think works best. In pycharm I was able
to configure paths for unit testing so I think we can setup just
about anything we want.

2) I would like to externalize the configuration of the database location
but I was going to wait until we had a bit more of the application and
some sort of configuration mechanism set up. For now the
'./honeyDB/honeyDB.sqlite' file just gets put in the location the scripts
are run
from. In the future I would like to have a config that allows us to decide
where to put this file (with a default) and then refer to that through
out. (Also in the unit tests every time I create the database I remove it
on the tear down)

I am by no means calling this done, just trying to get something started
that the plugin guys can call. I would also like to try connections
and catch errors as well as doing some other checking on the values being
inserted.I also think we may need to discuss if some of this
needs to be organized into a class.

Thanks,
Ben

**Pull request merged**
