### PR TITLE
Dina services ip2

### PR DESCRIPTION
**Pull request by dsteeve**
This adds the capability to do a rest call to an ipaddresses endpoint and get data about that ipaddress across all the ports being monitored.
Example call from postman would be:  http://127.0.0.1:8080/v1/analytics/ipaddresses/127.0.0.1?days=3

It also handles the new globalconfig that was refactored and fixes up some tests.

### CODE REVIEW

**Comment by dsteeve** [comment]
anyone have time to review??

**Comment by benphillips989** [comment]
Hey Dina I pulled this down, I noticed it wouldn't run on my machine until i installed dateutil? Not sure if we need to add this as a dependency somewhere. Also the SQL statements in the logs (at least for the http plugins) are going after the "local address" instead of "peer address". I think we want to pull back data by attacker right?

**Comment by benphillips989** [comment]
:+1:

**Comment by dsteeve** [comment]
ok, I added a new commit to validate the ipaddress given.  this should be a little more safer than before.

**Pull request merged**
